import * as IndexRoute from './scripts/routes/index.route.js'
import * as RouterLib from '../../../router.js'


RouterLib.addRoute({ pathname: '/', route: IndexRoute })

const forbiddenURLs = [
    'cloudflare.worker.js',
    '_actions_autogenerated.js',
]

const serverOnlyURLs = [
    '/tr',
    '/privacy_sandbox/pixel/register/trigger',
    '/track',
]

export {
    forbiddenURLs,
    serverOnlyURLs,
}